### ISSUE TITLE
Dealing with 7000+ ABCFile instances

### ISSUE THREAD

**Issue by UnfamiliarLegacy** [ArachisH/Flazzy#4]
Big fan of your library, it has saved me a lot of time.
I have one issue though, which is dealing with multiple `ABCFile` instances.

For Habbo it is always 2/3 instances and you can easily pick out the one that contains all classes / methods. 
However, I noticed if you compile the opensource habbo swf manually, you get 7000+ `ABCFile`s.

**Opensource swf**
![image](https://user-images.githubusercontent.com/74633542/114276896-f681c080-9a28-11eb-8ac5-016c99195b4b.png)

**Traditional swf**
![image](https://user-images.githubusercontent.com/74633542/114276909-0dc0ae00-9a29-11eb-95bf-f91548035546.png)

Both work fine normally, JPEXS / AS3 sorcerer shows code fine as well.

Do you have any idea how I can deal with them in such a way that it does not matter how many `ABCFile`s there are?

If you are open to chat about it, my discord is `Mikee#0055`.

**Comment by UnfamiliarLegacy** [comment]
I have overriden `Equals` and `HashCode` https://github.com/UnfamiliarLegacy/Flazzy/commit/4fcaf35a8ab767094eb551eeb7669c1a0bc3bfcb.
Now I can simply search through all abc files. Normally this wouldn't work because the ASMultiname references are not the same.
```csharp
public ASClass GetClass(ASMultiname multiname)
{
    foreach (var abcFile in _abcFiles)
    {
        var clazz = abcFile.GetClass(multiname);
        if (clazz != null)
        {
            return clazz;
        }
    }

    return null;
}
```

**Comment by ArachisH** [comment]
That's a lot of ABCs, I'll steal this if you don't make a PR.

**Comment by UnfamiliarLegacy** [comment]
Feel free to steal from my fork 😃 
Make sure to use the latest commit and not the one linked above.
